version: 0.1

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "<-- RUNTIME EXECUTION -->"
      - pip install --upgrade pip
      - pip install -r requirements.txt

artifacts:
  files:
    - '**/*'
